### ISSUE TITLE
Hot Water Tank change Operation 

### ISSUE THREAD

**Issue by ckortenhorst** [tadasdanielius/daikin_altherma#22]
When I change Operation to another variable I get following error 

![image](https://user-images.githubusercontent.com/5760635/158082676-6a275298-b6c8-4a9a-a563-41008b17b2a0.png)

![image](https://user-images.githubusercontent.com/5760635/158082686-9dcc6dac-101d-46c3-b50f-31f7523e40bd.png)

Also there does not seam to be a way to setup automation to use these Operations or change variables.

**Comment by tadasdanielius** [comment]
Probably the profile of the unit differs somehow. In order to address this I will try to add additional logging to see how the unit's profile looks like.

**Comment by tadasdanielius** [comment]
Could you provide more info? Please take a look at this [issue](https://github.com/tadasdanielius/daikin_altherma/issues/20#issuecomment-1122168446)

**Comment by theBOFH** [comment]
Hi @tadasdanielius, 
Not exactly the same error message but getting "Failed to call service number/set_value. 'IndoorTemperature'" when trying to change the temperature control. 
Ran v.1.1.4 and it looks like the .json's don't show  IndoorTemperature so guessing thats where the problem is. 
For context the its an Altherma2 with a BRP069A61 and configured to be controlled by an external thermostat  ("Ext RT control" 

The contents of the three files are
`
{"SyncStatus": "update", "UnitStatus": ["ErrorState"], "DateTime": {"DateTimeAdjustable": false}}
{"SyncStatus": "reboot", "Sensor": ["OutdoorTemperature", "LeavingWaterTemperatureCurrent"], "UnitStatus": ["ErrorState", "InstallerState", "WarningState", "EmergencyState", "TargetTemperatureOverruledState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating"], "LeavingWaterTemperatureOffsetHeating": {"maxValue": 10, "minValue": -10, "stepValue": 1, "settable": true}}, "Schedule": {}}
{"SyncStatus": "reboot", "Sensor": ["TankTemperature"], "UnitStatus": ["ErrorState", "InstallerState", "WeatherDependentState", "WarningState", "EmergencyState", "TargetTemperatureOverruledState"], "Operation": {"Power": ["on", "standby"], "OperationMode": ["heating"], "TargetTemperature": {"heating": {}}, "DomesticHotWaterTemperatureHeating": {"maxValue": 60.0, "minValue": 30.0, "stepValue": 1.0, "settable": false}, "powerful": ["0", "1"]}, "Schedule": {"Base": "action", "defaultScheduleAvailable": "false", "NameAdjustable": "false", "List": {"heating": [{"StartTime": {"stepValue": 10.0, "unit": "minute"}, "TargetTemperature": {"heating": {"maxValue": 60.0, "minValue": 30.0, "stepValue": 1.0}}, "Actions": ["StartTime", "TargetTemperature"], "maxActionsAllowed": 4}, ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], []]}}}
`

Is there any way to remove the indoor temperature?

**Comment by tadasdanielius** [comment]
Ok, I will look into it. Meanwhile if you try to disable entity maybe that would help as a workaround?

**Comment by wiklund75** [comment]
Hello!
Thank you for a fantastic program that makes it possible to control the Altherma 3 from HA.

I have a problem creating automations associated with this application.
I want Altherma 3 to stop producing hot water at a certain electricity price at Noordpool.

The value triggers the automation, but it do
<img width="989" alt="Skärmavbild 2022-09-16 kl  17 53 27" src="https://user-images.githubusercontent.com/113247403/190680793-66d2c764-a1fa-4ff9-b33e-8cb11f3fc63b.png">
es not turn off the water heater.
<img width="546
<img width="621" alt="Skärmavbild 2022-09-16 kl  17 57 35" src="https://user-images.githubusercontent.com/113247403/190680823-40bf51da-78fa-4f6f-a56a-7de3b36a0f4d.png">
" alt="Skärmavbild 2022-09-16 kl  17 53 50" src="https://user-images.githubusercontent.com/113247403/190680810-17f43ef3-6bb0-4f5b-b42f-c64fc5b40c86.png">

It comes instead with an error message.
Pictures attached!

Best regards / Niklas

**Comment by wiklund75** [comment]
> But the better way to achieve what you want is to call service "Water Heater: Set Operation Mode". When creating automation in the actions choose `call service` and search for Water Heater
> 
> <img alt="image" width="1038" src="https://user-images.githubusercontent.com/8099860/190687290-26703274-7902-469b-82e4-e2ee98b34d72.png">
> 
> Choose `Water Heater: Set Operation Mode` In `Targets` area click `choose entity` and search for the entity. Normally you should see something like this
> 
> <img alt="image" width="1029" src="https://user-images.githubusercontent.com/8099860/190687513-89762eca-6b98-421b-9e18-6125ed664234.png">
> 
> Finally in Operation Mode type `off`
> 
> Here is the picture how it should look
> 
> <img alt="image" width="1065" src="https://user-images.githubusercontent.com/8099860/190687932-f401d5c7-6f9f-4504-b392-5e30eed1c7be.png">
> 
> In operation mode you should be able to type `on` `off` or `performance` if supported

Many thanks for your answer. Problem solved! Great job!
