### ISSUE TITLE
Error BadLogger 

### ISSUE THREAD

**Issue by thecobra666** [tadasdanielius/daikin_altherma#78]
Lately I'm receiving this error message in the logs: Bad logger message: Failed to update the device status with error Received message 8:1007 is not str ((TypeError('Received message 8:1007 is not str'),))

Running latest package and HA 2023.9.2.

**Comment by tadasdanielius** [comment]
Is it just logging issue or you experiencing functionality problems as well? Difficult to tell where exactly it is originating from stack trace would help.

**Comment by thecobra666** [comment]
> Is it just logging issue or you experiencing functionality problems as well? Difficult to tell where exactly it is originating from stack trace would help.

It is a logging issue.

**Comment by tadasdanielius** [comment]
I did some investigating and it seems that the issue may be due to the device returning an empty response, which isn't being handled gracefully. It's likely safe to disregard this if everything is functioning as expected. How long it takes for the changes to appear in HA if you do some changes on the heatpump or via onecta app?

**Comment by thecobra666** [comment]
> I did some investigating and it seems that the issue may be due to the device returning an empty response, which isn't being handled gracefully. It's likely safe to disregard this if everything is functioning as expected. How long it takes for the changes to appear in HA if you do some changes on the heatpump or via onecta app?

Almost instant. Not more then a second or 2.
